version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: Build ...
          command: sleep 5 && echo ok

      - deploy:
          name: Deploying ...
          command: echo deploying stuff

workflows:
  version: 2
  pipeline:
    jobs:
      - build
